### ISSUE TITLE
Add `all` method

### ISSUE THREAD

**Issue by lukeed** [lukeed/trouter#1]
Should either append to all `{METHOD}` lists, or every `{METHOD}` action should look inside `all` too.

**Comment by ianwalter** [comment]
Is this what you were thinking for the second option? Add 'all' as a separate method, and then in `find()` do something like:
```js
let arr = match(url, [...this.routes[method], ...this.routes['all']])
```

**Comment by lukeed** [comment]
Yup, effectively! I added this in a branch last week. About to roll it out for Polka@0.4

Trying to do a few things at once in that release.
