### ISSUE TITLE
Access to original route string?

### ISSUE THREAD

**Issue by saibotsivad** [lukeed/trouter#18]
I'm making some tooling that maps an OpenAPI definition to a Trouter (specifically Polka) router/app thing, but what I'm missing when calling the handler is the `route`, e.g. `/things/:thingId`, so that I can map that back to a path definition.

It looks like that info is not passed to `routes` on [line 29](https://github.com/lukeed/trouter/blob/master/index.mjs#L29) so that part would be easy enough to add:

```diff
- this.routes.push({ keys, pattern, method, handlers });
+ this.routes.push({ keys, pattern, method, handlers, route });
```

but... I'm not sure how that would be handed back to the `handlers` array, since that's just an array of functions from `fns`, so the only way to do that is something horrible like `tmp.handlers[0].route = route` or whatever.

The only other way that comes to mind is changing the returned object:

```diff
- return { params, handlers };
+ return { params, handlers, routes };
```

where the `routes` would probably have to be a list of route strings, e.g. `/things/:thingId` that was index-matched to the `handlers` list. That doesn't feel super great, but it's ... not horrible? 🤔

**Comment by saibotsivad** [comment]
(Note for thinking purposes, I'd also like this property made available in Polka, but my code-reading indicated the root issue is in Trouter, so I'm starting here.)

**Comment by lukeed** [comment]
I'm not particularly keen on changing anything internal here, tbh. How about the first `handler` writes itself? You can overload the `add` method and do it that way:

Works with polka:

```js
let app = polka();

let toAdd = app.add.bind(app);

app.add = function (m, r, ...h) {
  let route = String(r);
  // Custom function to save route
  // where & how you want it
  let custom = (req, res, next) => {
    req.$route = route;
    next(); // done
  };
  return toAdd(m, r, custom, ...h);
}
```

You can do the same thing in a Trouter app, but given that the `Trouter` class is exposed directly, you can just extend it as your own & call `super.add` instead. Of course, that ends up being exactly the same thing, just a syntax difference.

The benefit of this versus your proposed changes, is that you can put the information exactly where you want it and still at time of definition. Making it part of the return object (from Trouter.find) we'll still require you to massage the values into place anyway, and would be ignored / useless by the majority of users

**Comment by saibotsivad** [comment]
Okay now that's pretty clever, I'll give it a go and see if I can make it work.

I'm of a similar mind, the internals are pretty clean and I'm not particularly wanting to change them, unless it can be done while keeping the same clean simplicity of course.

This is starting to turn into a Polka discussion, apologies for that 😅 the problem is that I feel like the clearest design would be adding a middleware that takes an OpenAPI definition and adds properties based on route/query parameters:

```js
import openapiParams from 'my-openapi-mapper-thing'
import polka from 'polka'
import definition from './openapi.json'

const app = polka()

app.use(openapiParams(definition))

// add routes etc.
```

Ideally I'd like to handle the parameter transforms (e.g. path/query params to types, etc.) inside that `openapiParams` middleware, but with what you're suggesting that wouldn't reeeeally be possible, I think?

With the pattern you suggest, instead of a normal middleware I think it'd have to be like:

```js
// my-lib-thing
export const rewriter = app => {
    let toAdd = app.add.bind(app)
    app.add = function (m, r, ...h) {
        //... what you wrote
    }
}
export const middleware = definition => (req, res, next) => {
    //... add params to req based on $route
}
```

and then

```js
import { rewriter, middleware } from 'my-lib-thing'
import polka from 'polka'
import definition from './openapi.json'

const app = polka()
rewriter(app)

app.use(middleware(definition))
// etc
```

That isn't a *horrible* solution, but it really feels like I'm stepping outside the Polka design pattern with that approach.

Do you have clever ideas to make this cleaner, or do you think that rewriter/middleware approach seems reasonable?

**Comment by lukeed** [comment]
I assume you want to keep `'my-lib-thing'` framework agnostic, otherwise you'd include Polka directly as a dependency and hide away the rewrites entirely, in which case it wouldn't matter what/how you do it. I don't think your last snippet is bad at all, although it could be consolidated into this:

```js
import { OpenAPI } from 'lib';
import routes from './openapi.json';

const app = polka();

OpenAPI(app, routes);
// ^ rewriter + middleware, calls `app.use` internally
```

And because of this agnosticism, you'd have to do the the same thing for Express, Fastify, etc anyway. None of them expose the route definition directly anyway, so you'd always need to do some kind of wrapping/preprocessing anyway.

If you were to pick a framework directly, you could lean more into the done-for-you camp. You could also expose a wrapped version of the underlying class. Express exports `Router`, which you can extend. And you can actually get to Polka's class too:

```js
const Polka = polka().constructor;

class OpenAPI extends Polka {
  constructor(definitions, options) {
    super(options);
    // some definitions processing
  }
  add(method, route, ...handlers) {
    super.add(/* same as before */);
  }
}

// --- 

const App = new OpenAPI(definitions);
//=> App is a Polka instance
App.get('/', (req, res) => {
  res.end('Hello');
});
```

> Ideally I'd like to handle the parameter transforms (e.g. path/query params to types, etc.) inside that openapiParams middleware, but with what you're suggesting that wouldn't reeeeally be possible, I think?

I don't currently know what this means. I'd need to see an example to help direct you towards something

**Comment by saibotsivad** [comment]
Good thoughts there, thanks. I'll explore these ideas a bit and see where I land, but in any case I agree that changing Trouter internals isn't the solution. Thanks!
