### ISSUE TITLE
Ability to add sub-routers?

### ISSUE THREAD

**Issue by iCyberon** [lukeed/trouter#2]
It would really be great to have ability to add sub-routers. Don't know if it's on your roadmap, if it is I can work on it and submit a PR.

**Comment by iCyberon** [comment]
Thanks for the answer @lukeed. 

The problem is that once have more than certain amount of routes it becomes "messy" to manage child routes. Here's an example of what I mean.

```
/posts
/posts/:pid
/posts/:pid/comments/
/posts/:pid/comments/:cid
/posts/:pid/comments/:cid/likes
/posts/:pid/comments/:cid/likes/:lid
```

This will become:
```
// main
polka()
.use(posts)
.listen(PORT).then( _ => {
	console.log(`> Running on localhost:${PORT}`);
});

// posts
polka()
.get('/posts, noop )
.get('/posts/:pid', noop )
.use(comments)
.listen(PORT).then( _ => {
	console.log(`> Running on localhost:${PORT}`);
});

// comments
polka()
.get('/posts/:pid/comments, noop )
.get('/posts/:pid/comments/:cid, noop )
.use(likes)
.listen(PORT).then( _ => {
	console.log(`> Running on localhost:${PORT}`);
});

// ...
```

As you can see we're basically repeating parent route path for every child router. It just hit me, `polka` can accept `base` option inside opts and prepend it (inside Trouter's constructor) to every registered handler.

What do you think?

**Comment by lukeed** [comment]
No problem~

Yeah, for Trouter it gets messy. This is why this logic belongs to the server itself, because there are a lot of different ways one may want to handle this &mdash; both defining the routes & retrieving them.

This isn't live yet, but Polka `0.3.0` has greatly improved sub-app support. Your example will look like this:

```js
let posts = 
  polka()
    .get('/', noop)
    .get('/:pid', noop)
    .use('comments', 'comments')

let comments = 
  polka()
    .get('/', noop)
    .get('/:cid', noop)
    .use('likes', likes)

// main
polka()
  .use('posts', posts)
  .listen(PORT).then( _ => {
    console.log(`> Running on localhost:${PORT}`);
  });
```

> By the way, you should only be calling `listen` on the main app.

**Comment by iCyberon** [comment]
Yeah, that was copy-paste error. Unless I'm missing something `use` is a variadic function and I like it, changing `use` was my first idea, but dropped it because of that. 

Apparently changing `add` a little bit is enough.

```js
add(method, pattern, handler) {
    // Save decoded pattern info
    this.routes[method].push(parse(this.opts.base || '' + pattern));
    // Save route handler
    this.handlers[method][this.opts.base || '' + pattern] = handler;
    // Allow chainable
    return this;
}
```

**Comment by lukeed** [comment]
In the next version, yes, it's variadic. 

You should update the `pattern` once & early. Also need to apply logic to make sure you're not ending up with double slashes somewhere.
