### ISSUE TITLE
TypeScript definitions

### ISSUE THREAD

**Issue by luvies** [lukeed/trouter#7]
I noticed that there were TS definitions in this package, but they were removed in favour of using DefinitelyTyped, however I cannot find the definitions in that package. Are they under a different name, or have they not been added, and if not, could you add in the definition file again (I think it's normally preferable for the package to have the definitions rather than rely on DefinitelyTyped anyway)? I can provide a definition file for this package if you wanted to add them back in to here, since I needed them anyway (I also made changes to it that made the definitions better to use).

**Comment by lukeed** [comment]
They are now available via [`@types/trouter`](https://www.npmjs.com/package/@types/trouter) thanks to @stahlstift (and @fwilkerson in the past) 🙌 

![source](https://user-images.githubusercontent.com/5855893/54165335-7b9ae580-441d-11e9-8032-1f90829f088e.gif)
