### ISSUE TITLE
Incorrect params parsing?

### ISSUE THREAD

**Issue by mhkeller** [lukeed/trouter#8]
With a route like the following, I expect the last `:y` parameter to not include `.mvt` but it's currently reading `:y.mvt` as my param key and including the string `.mvt` in the param value.

```js
polka()
  .get('/:z/:x/:y.mvt', async (req, res) => {
    const { params } = req;
    console.log(params.y) // undefined
    console.log(params['y.mvt'] // 'myY.mvt'

    // workaround
    const y = params['y.mvt'].replace('.mvt', '');
    console.log(y) // 'myY'
```

I'm porting an app over from express that parsed this format as expected. But maybe this URL structure is no good to begin with!

**Comment by lukeed** [comment]
Transferred the issue as Trouter is technically the router.

I _did_ come up with a better solution, which will be released at a later date. For now, the previous `matchit` solution will suffice.

> Congrats on an amazing article @mhkeller 👏

**Comment by lukeed** [comment]
Technically closed via `matchit@1.0.7` but leaving this open until I merge the solution I'm happier with.

**Comment by mhkeller** [comment]
Ah thanks! It was a fun one to work on. Very cool. Thanks for continuing to commit the brain cells to this one.

**Comment by lukeed** [comment]
FInally~
